# Generated by Django 3.1.2 on 2020-11-07 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvErrorFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(blank=True, choices=[('mysql', 'MySQL'), ('postgres', 'PostgreSQL')], max_length=20)),
                ('server_username', models.CharField(blank=True, max_length=30)),
                ('server_port', models.IntegerField(blank=True, verbose_name=django.db.models.fields.PositiveIntegerField)),
                ('server_host', models.CharField(blank=True, max_length=100)),
                ('server_database', models.CharField(blank=True, max_length=50)),
                ('server_table', models.CharField(blank=True, max_length=50)),
                ('process_state', models.CharField(blank=True, choices=[('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], max_length=20)),
                ('uploaded_file', models.FileField(blank=True, upload_to='uploads')),
                ('uploaded_file_hash', models.CharField(blank=True, max_length=32)),
                ('error_file', models.FileField(blank=True, upload_to='error_files')),
                ('commit', models.BooleanField(blank=True, default=False)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
